[package]
name = "include-crypt"
version = "0.1.0"
authors = ["not-matthias <26800596+not-matthias@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
const-random = "0.1.8"

include-crypt-codegen = { path = "../codegen" }

